default_language_version:
  python: python3

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ^.vscode/
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - numpy
          - torch
          - types-pyyaml
          - '--index-url=https://download.pytorch.org/whl/cpu'
          - '--extra-index-url=https://pypi.python.org/simple'
        exclude: docs/.*|tests/.*

  - repo: 'https://github.com/codespell-project/codespell'
    rev: v2.2.4
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        # exclude: ^docs/|tests/.*
      # Run the formatter.
      - id: ruff-format
